### ISSUE TITLE
CollageImageView cannot be cast to androidx.recyclerview.widget.RecyclerView

### ISSUE THREAD

**Issue by Hussnainhashmi** [GrishinSergey/CollageImageView#6]
I'm setting list of bitmap to collage image view but getting this warning

collageIv.setImages(getBitmapList());

**Comment by GrishinSergey** [comment]
Hello, @Hussnainhashmi ,
Yes, This can happens because, in your code you somewhere tries to cast 'collageIv' to RecyclerView. Can you provide full source code, so we can check it?
