### ISSUE TITLE
Corner radius

### ISSUE THREAD

**Issue by DmitryDAN1** [GrishinSergey/CollageImageView#7]
It would be cool if you add the ability to set the corner radius

**Comment by GrishinSergey** [comment]
Hello, @DmitryDAN1 . Yeah, it's good idea, thank you. Will add it)

**Comment by GrishinSergey** [comment]
Hello, @DmitryDAN1 . I made new release v2.0.1. You can try it. Also there is feature with rounded corners)

**Comment by DmitryDAN1** [comment]
> Hello, @DmitryDAN1 . I made new release v2.0.1. You can try it. Also there is feature with rounded corners)

Thanks, looks cool!
But I found a small bug when numbers are displayed rounding is missing
[screen](https://prnt.sc/127lefc)

**Comment by GrishinSergey** [comment]
> > Hello, @DmitryDAN1 . I made new release v2.0.1. You can try it. Also there is feature with rounded corners)
> 
> Thanks, looks cool!
> But I found a small bug when numbers are displayed rounding is missing
> [screen](https://prnt.sc/127lefc)

Thank you for report will fix it soon)

**Comment by GrishinSergey** [comment]
Hello, @DmitryDAN1 , I made update with fixes. You can check them. It is version v2.0.2
